name: Generate extspam
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate "extspam"
        run: docker run --rm ghcr.io/bluesky-07/wechat-token:latest > extspam.txt
      - name: Store as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: extspam.txt
          path: extspam.txt
      - name: Output Result
        run: cat extspam.txt
