name: Generate extspam
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - run: ./run.sh
